### ISSUE TITLE
Unused class rule when building -- seems to be a typo in FD Selection products dict xml

### ISSUE THREAD

**Issue by calcuttj** [DUNE/dunereco#59]
See [here](https://github.com/DUNE/dunereco/blob/develop/dunereco/FDSelections/FDSelectionData/classes_def.xml#L13)

`  <class name="art::Ptr<pandnusel::PandoraNuSelection>" />`
should be  (I believe)
`  <class name="art::Ptr<pandoranusel::PandoraNuSelection>" />`

**Comment by calcuttj** [comment]
Some background to this. When building recently, I noticed this warning 

<pre>
[1661/3980] Generating dictionary files for target dunereco_FDSelections_FDSelectionData
Warning: Unused class rule: art::Ptr<pandnusel::PandoraNuSelection>
</pre>

Would be good to automatically catch this when compiling

**Comment by absolution1** [comment]
@imawby should comment.
In the interest of getting the fix out there (and how clear the fix looks) I've approved the associated PR.

**Comment by imawby** [comment]
Hello, yes that fix is correct Jake - thank you! Dom when you say that you've approved the associated PR, does this mean that the fix has been implemented? Thanks.

**Comment by absolution1** [comment]
https://github.com/DUNE/dunereco/pull/60

I've rubber stamped Jake's PR that implements the small fix.

**Comment by tomjunk** [comment]
Looks like this issue is addressed.
